### ISSUE TITLE
Incorrect progress counting

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/symfony-bundle#148]
It's a bit tricky, but I think it could be considered as incorrect progress counting, let me show an example:

Suppose, I have 3 different translation keys in total: `foo`, `hello`, and `world`.
And I have 2 languages, but each one has only 2 different of them:
```yml
# messages.en.yml
foo: bar
hello: Hello
```

```yml
# messages.ru.yml
hello: Привет
world: Мир
```

i.e. if 2 of them are translated into English and another 2 of them are translated into Russian - I have for both:
> Total progress for this language: 100%

But I expected to see 66% for both
