### ISSUE TITLE
Symfony 4 - admin/_trans - Unable to find template "TranslationBundle:WebUI:base.html.twig"

### ISSUE THREAD

**Issue by lsv** [php-translation/symfony-bundle#168]
Unable to find templates to the WebUI

```
Unable to find template "TranslationBundle:WebUI:base.html.twig" (looked into: /lsv/templates,  /lsv/vendor/symfony/twig-bridge/Resources/views/Form) in @Translation/WebUI/index.html.twig at line 1.
```

Twig configuration

```yaml
twig:
    paths:
        - '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form.html.twig']
```

form.html.twig is in my `src/templates/form.html.twig` and just extends `bootstrap_4_layout.html.twig`

**Comment by lsv** [comment]
By updating my twig config to

```yaml
twig:
    paths:
        '%kernel.project_dir%/vendor/php-translation/symfony-bundle/Resources/views': TranslationBundle
```

And updating all `{% extends "TranslationBundle:WebUI:base.html.twig" %}` to `{% extends "@TranslationBundle/WebUI/base.html.twig" %}` (adding a @ infront)

It now works, though properly not the best way, and will properly break symfony < 4, by adding the @ infront of the extends
