### ISSUE TITLE
[Edit in place] Trans twig extension not using the configured activator

### ISSUE THREAD

**Issue by DPvic** [php-translation/symfony-bundle#181]
Working with:
- symfony/framework-bundle: 3.4.3
- symfony/translation: 3.4.3
- php-translation/symfony-bundle; 0.5.0

Hi, i'm trying to use the edit in place feature but the content seems to allways be marked as "untrasnlatable"
```yaml
translation:
  locales: '%locales%' #['en','es]
  symfony_profiler:
    enabled: true
  webui:
      enabled: true
  edit_in_place:
      enabled: true
      config_name: default # the first one or one of your configs
      activator: App\Translation\RoleActivator 
  configs:
      app:
          dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src","%kernel.project_dir%/vendor/friendsofsymfony"]
          external_translations_dir: "%kernel.project_dir%/vendor/friendsofsymfony/user-bundle/Resources/translations"
          output_dir: "%kernel.project_dir%/translations"
          excluded_names: ["*TestCase.php", "*Test.php"]
          excluded_dirs: [cache, data, logs]
```
The activator is working fine, but all the content is printed as untranslatable, ig: 
                <div>🚫 home|home.test 🚫</div>
                <div>🚫 FOSUserBundle|layout.register 🚫</div>
I can't find anywhere in the docs why the content is "untranslatable", for instance, the content can be updated at the profiler and at /admin/_trans/

After taking a look at the listener
https://github.com/php-translation/symfony-bundle/blob/305f4b186e95e4ebbaaafc50ba90a9f25dff0e5c/EventListener/EditInPlaceResponseListener.php#L88-L93
I saw the original html as: 
```
<x-trans data-key="home|home.test" data-value="test" data-plain="test" data-domain="home" data-locale="es">test</x-trans>
<x-trans data-key="FOSUserBundle|layout.register" data-value="Registrar" data-plain="Registrar" data-domain="FOSUserBundle" data-locale="es">Registrar</x-trans>
```
What I am missing?

**Comment by bocharsky-bw** [comment]
Hm, I used to see this error before... but I do some simple actions and it works now for me.

1. Try to clear the cache with `rm -rf var/cache/*`
2. Open that page in Chrome Incognito mode

IIRC, I did nothing except this

**Comment by DPvic** [comment]
I followed your tips, after complety removing the cache `rm -rf var/cache/*` and entering in Incognito mode (Chrome and Firefox) it didn't work.  

The I procceded to change the default locale from` 'es' `to` 'en'` and it worked! Changed back to 'es' again and it still works. Now I can't reproduce the error, even after going back to the same config and wiping the cache. 

The output html before the `EditInPlaceResponseListener` seems the same: 

`<x-trans data-key="home|home.test" data-value="test" data-plain="test" data-domain="home" data-locale="es">test</x-trans>`

Anyways, thanks for the great library

**Comment by bocharsky-bw** [comment]
Aha, maybe I did it too, don't 100% remember it, and have no idea why it works tricky for the first run

**Comment by DPvic** [comment]
Well I finally found It. 

My config looks like: 
```
 #services.yaml
  App\Translation\RoleActivator:
     arguments: ["@security.authorization_checker"]
```

And the config: 

```
#config.yaml
translation:
  edit_in_place:
      activator: App\Translation\RoleActivator 
  #...
```

Now my activator is used for the following services: `php_translation.edit_in_place.response_listener` and  `php_translator.edit_in_place.xtrans_html_translator` but not for the `php_translation.edit_in_place.extension.trans `  wich allways uses the default `@php_translation.edit_in_place.activator`

So, the edit in place is activated, the assets are loaded fine but the output of the `trans` filter is not marked as html safe, so it is escaped.
Taking a look at the extension we can see it:

https://github.com/php-translation/symfony-bundle/blob/d9d040435c2dfe6e2ac471022cb197822baf1e9d/DependencyInjection/TranslationExtension.php#L180-L197

Wich could be easily be fixed as: 

```
    private function enableEditInPlace(ContainerBuilder $container, array $config)
    {
        $name = $config['edit_in_place']['config_name'];

        if ('default' !== $name && !isset($config['configs'][$name])) {
            throw new InvalidArgumentException(sprintf('There is no config named "%s".', $name));
        }

        $activatorRef = new Reference($config['edit_in_place']['activator']);

        $def = $container->getDefinition('php_translation.edit_in_place.response_listener');
        $def->replaceArgument(0, $activatorRef);
        $def->replaceArgument(3, $name);
        $def->replaceArgument(4, $config['edit_in_place']['show_untranslatable']);

        $def = $container->getDefinition('php_translator.edit_in_place.xtrans_html_translator');
        $def->replaceArgument(1, $activatorRef);

        #Use the configured service for the trans extension
        $def = $container->getDefinition('php_translation.edit_in_place.extension.trans');
        $def->addMethodCall('setActivator',[$activatorRef]);
    }
```
