### ISSUE TITLE
Exclude files for translation:delete-obsolete command

### ISSUE THREAD

**Issue by DidierLmn** [php-translation/symfony-bundle#186]
I use [this bundle ](https://github.com/willdurand/BazingaJsTranslationBundle) to expose certain translations to the client side. 

Since these translations are only used in JavaScript files, they are marked as obsolete. Is there an option to exclude the translation file(s) where the JS translations are located (for example `js.en.xlf`) when executing `translation:delete-obsolete command`?

**Comment by Nyholm** [comment]
Are your JS translations in a different domain?
If so, could you use the config option `blacklist_domain` to exclude that domain from the bundles config? Then the bundle will not touch those translations.

If you still need say, the webUI, then you should create a separate configuration. 
```
translation: 
  configs: 
      default: 
          blacklist_domain: "javascript"
          # stuff
       js: 
          # other stuff
```

Im not sure something this will work. Could you give it a try and come back with your solution. I'll be happy to put it in the docs.

**Comment by DidierLmn** [comment]
Thanks for the suggestion, I was unaware of the `blacklist_domain` option.

I've tried it, but it doesn't seem to be able to work unfortunately. I've used this as a config in `packages/php_translation.yaml`:


```
translation:
    locales: '%locales%'
    configs:
        default:
            blacklist_domain: "javascript"
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
```

As you can see I've blacklisted the `javascript` domain, however it still shows up in the webUI

![screen shot 2018-02-05 at 09 48 49](https://user-images.githubusercontent.com/15478968/35795593-e29fc2d6-0a59-11e8-9eca-b8e0410012af.png)

I've tried using `blacklist_domains: ["javascript"]` instead, but that doesn't seem to work either. I've cleared the Symfony and browser cache multiple times and restarted my server.

I'm not getting any errors or anything. Is it possible there's a bug in with the `blacklist_domain` option? Or is there anywhere else I can check or something I could've done wrong?
Thanks
