### ISSUE TITLE
Symfony4 doesn't pick up commands automatically

### ISSUE THREAD

**Issue by rpkamp** [php-translation/symfony-bundle#188]
Unlike earlier versions, Symfony 4 does not automatically register commands in the `Bundle\Command` namespace, so these should be registered by the bundle explicitly.

For those with the same problem, a temporary workaround is to register them by adding this to your service definition:

```yaml
Translation\Bundle\Command\:
    resource: 'path/to/vendor/php-translation/symfony-bundle/Command/*'
    tags: [console.command]
```
