### ISSUE TITLE
[Profiler] On message edit, routes.[currentLocale].xlf is created

### ISSUE THREAD

**Issue by welcoMattic** [php-translation/symfony-bundle#212]
Steps to reproduce

- I use JMSi18nRoutingBundle, for which I have created routes.fr.yaml and routes.en.yaml
- When I add a new key, then I edit the message from the Profiler, a routes.fr.xlf is created while it is useless.

Let me know if I have to investigate more than that.

### Config

```yaml
translation:
    locales: '['fr', 'en']'
    edit_in_place:
        enabled: false
    configs:
        default:
            dirs: ['%kernel.project_dir%/templates', '%kernel.project_dir%/src']
            output_dir: '%kernel.project_dir%/translations'
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs]
            remote_storage: ['php_translation.adapter.loco']

translation_adapter_loco:
    index_parameter: 'name'
    projects:
        website:
            api_key: '%env(LOCO_MESSAGES_API_KEY)%'
            domains: ['messages', 'validators']

```
