### ISSUE TITLE
Inherit existing translations

### ISSUE THREAD

**Issue by disjfa** [php-translation/symfony-bundle#228]
When i set up a symfony project i like to use existing bundles (fos user, knp paginator eq). But when i import translations the existing translations extracted are empty.

```xml
<segment>
  <source>resetting.check_email</source>
  <target></target>
</segment>
```

Can the extractor to be set up to extract the translations, and when a translation exists in the bundle we include the base translation on extract?

```xml
<segment>
  <source>resetting.check_email</source>
  <target>An email has been sent to %email%. It contains an activation link you must click to activate your account.</target>
</segment>
```

Or am i missing a flag that does just this?

**Comment by mrehanali** [comment]
Any update here?

**Comment by Nyholm** [comment]
Hey. Sorry for the late reply. 
This is already supported. See the config key `external_translations_dir`. 

You specify where we should load existing translations and they will be included in the dump. 

I see that the docs is missing for this. Could you provide a PR to the documentation?

**Comment by Aerendir** [comment]
Just in case someone comes to this issue searching for a way to translate third-party bundle or use their already provided translations...

In `config/packages/php_translation.yaml` configure the third party bundle directory where translations reside.

This is always `Resources/translations`.

So, to get loaded in `php-translation` the translations of `FOSUserBundle`, use this config:

```yaml
# config/packages/php_translation.yaml

translation:
  locales: ["it"]
  ...
  configs:
    app:
      ...
      # Use the external_translations_dir to set the path to the "translations" of FOSUserBundle
      external_translations_dir:
        - "%kernel.project_dir%/vendor/friendsofsymfony/user-bundle/Resources/translations"
```

@Nyholm , I'd like to submit a PR to add this information to the documentation but there is no page mentioning the integration with third-party bundles: any guidance about where to add this information?

Or I do something at my will? :P
