### ISSUE TITLE
Invalid resource provided: "1.2"; Errors: [ERROR 1845] Element '{urn:jms:translation}reference-file

### ISSUE THREAD

**Issue by grekpg** [php-translation/symfony-bundle#261]
Symfony 4.1 (upgraded from 3)

```
translation:
    locales: ["en","pt"]
    edit_in_place:
        enabled: false
#        activator: php_translation.edit_in_place.activator
#        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
```
Routing

```
_translation_webui:
    resource: "@TranslationBundle/Resources/config/routing_webui.yml"
    prefix:  /admin
```
Get errors on any page and any command in terminal

   Invalid resource provided: "1.2"; Errors: [ERROR 1845] Element '{urn:jms:translation}reference-file': No matching global element declaration available, but demanded by the strict wildcard. (in /application/public/ - line 12, column 0) [ERROR 1845] Element '{urn:jms:translation}reference-file': No matching global element declaration available, but demanded by the strict wildcard. (in /application/public/ - line 13, column 0) [ERROR 1845] Element '{urn:jms:translation}reference-file': No matching global element declaration available, but demanded by the strict wildcard. (in /application/public/ - line 20, column 0) [ERROR 1845] Element '{urn:jms:translation}reference-file': No matching global element declaration available, but demanded by the strict wildcard. (in  ......

**Comment by pimolo** [comment]
php-translation is trying to read translations catalogues formatted by the JMSTranslationBundle (I guess that you used to use it before) but it's a different schema, so you have these validations errors.

This lib may help you to convert them into the standard format:
https://github.com/php-translation/converter

I already experienced switching from JMSTranslationBundle to php-translation, so tell me if you encounter other issues.

**Comment by grekpg** [comment]
I install php-translation/converter dev-master (0.1.0 have dependency issues) 
Run 
` ./vendor/bin/translation-converter translation:convert translations translations-new --format=jms`
but files is not created - any message 

Translation files I have in translations/messages.pt.xliff
I create also translations-new/ empty directory 

command from manual 

```
./vendor/bin/translation-converter translation:convert translations translations-new jms

                                                                              
  Too many arguments, expected arguments "command" "input_dir" "output_dir".  
```
     

without format : 

```
 ./vendor/bin/translation-converter translation:convert translations translations-new

In XliffFileLoader.php line 186:
                                                                                                                                                                                                                        
  Invalid resource provided: "1.2"; Errors: [ERROR 1845] Element '{urn:jms:translation}reference-file': No matching global element declaration available, but demanded by the strict wildcard. (in /home/grek/Phpstorm  
  Projects/env/ - line 28, column 0)                                                                                                                                                                                
                                                                                                                                                                                                                        

translation:convert [--format FORMAT] [--] <input_dir> <output_dir>

```

**Comment by grekpg** [comment]
I convert my files in https://localise.biz/free/converter/yaml-to-xliff there is many formats but still dont see my translations. 

My config 

```
translation:
    locales: ["pl", "pt", "en"]
    symfony_profiler: # must be placed in config_dev.yml
        enabled: true
    auto_add_missing_translations:
        config_name: 'default'
    webui:
        enabled: true
    edit_in_place:
        enabled: true
        config_name: default # the first one or one of your configs
#        activator: php_translation.edit_in_place.activator
    configs:
        app:
            dirs: ["%kernel.root_dir%/../translations"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
        test:
            dirs: ["%kernel.root_dir%/../AppBundle", "%kernel.root_dir%/../translations"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]

```


```
 php bin/console translation:extract test

In FormTypePlaceholder.php line 54:
                                                                   
  Notice: Undefined property: PhpParser\Node\Expr\Ternary::$value  
                                                              
```
I try just import xliff file - app use only translations/ with messages.pt.xlf 
for test i rename to messages.pt.xliff same results 

```
php bin/console translation:extract app
 ------------------------ ------- 
  Type                     Count  
 ------------------------ ------- 
  Total defined messages   0      
  New messages             0      
  Errors                   0      
 ------------------------ ------- 


```
