### ISSUE TITLE
Translation updated always even file is not writable ....

### ISSUE THREAD

**Issue by grekpg** [php-translation/symfony-bundle#262]
Im moved from JMSTranslations, now everything work but this web ui give my 

Translation updated

When i change text in web interface event file is not writable so translation is not saved - it can cost translators a lot of work !

Here is my config 

```
translation:
    locales: ["pl", "pt", "en"]
    symfony_profiler: # must be placed in config_dev.yml
        enabled: true
    auto_add_missing_translations:
        config_name: 'default'
    webui:
        enabled: true
    edit_in_place:
        enabled: false
        config_name: default # the first one or one of your configs
        activator: php_translation.edit_in_place.activator
    configs:
        default:
            dirs: ["%kernel.root_dir%/../templates", "%kernel.root_dir%/../AppBundle/Service", "%kernel.root_dir%/../AppBundle/Controller",  "%kernel.root_dir%/../AppBundle/Resources"]
            output_dir: "%kernel.root_dir%/../translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
```
