### ISSUE TITLE
auto_add_missing_translations in production on Symfony 4

### ISSUE THREAD

**Issue by DamienVS** [php-translation/symfony-bundle#283]
Hello,
I want to activate the "auto_add_missing_translations" in a production environment (live data to translate)

In the doc, there' a specific tweak  to make the config running without the dev-bar :
```
translator.data_collector:
    class: Symfony\Component\Translation\DataCollectorTranslator
    decorates: translator
    arguments: ['@translator.data_collector.inner']
```
However that doesn't work in Symfony4, (or i can't find the place I'm supposed to put that config, maybe)

Can someone with deeper knowledge of the bits and bolt help me with this, so i can update the docs ?
