### ISSUE TITLE
Web UI generates xlf files instead of xliff

### ISSUE THREAD

**Issue by faizanakram99** [php-translation/symfony-bundle#302]
Web UI generates xlf files instead of xliff files. I am using xliff file format

**Comment by faizanakram99** [comment]
Okay I found the reason,

it is Translation\SymfonyStorage\FileStorage class, the xliff version defaults to 2.0 if it is not passed in via constructor (4th parameter $options) but then Translation\SymfonyStorage\FileStorage is a service and is automatically instantiated with no control over its arguments. 

Is there an easy way to configure options(xliff) or do I need to decorate this service ?

Did something similar for #301 , overrode service definition for adding Dumper.

**Comment by faizanakram99** [comment]
Decorating service won't help either because $options is a private property and there is no way to specify $options except constructor.

I have to literally rewrite the whole class in Decorating service.

**Comment by odolbeau** [comment]
You can override the configuration of the local storage directly in your configuration:

```yaml
translation:
  configs:
    your_config_name:
      local_file_storage_options:
        xliff_version: "1.2"
        output_format: "xliff"
```

Tell me if it's solved your problem. :)
