### ISSUE TITLE
Problem with extractor config

### ISSUE THREAD

**Issue by Suvres** [php-translation/symfony-bundle#437]
in extractors.yaml on line 4
```yaml
services:
    _defaults:
        bind:
            $metadataFactory: '@validator'
```
this bind parameter is unnecessary. The good practice is add `'@validator'` as elements in arguments, because when I need change the ValidationAnnotation Class that I have error that I have unused bind parametr

and this parametr should be in
```yaml
    Translation\Extractor\Visitor\Php\Symfony\ValidationAnnotation:
         arguments: ['@validator']
```
