### ISSUE TITLE
Symfony 6.4 ReferenceError: Sfjs is not defined

### ISSUE THREAD

**Issue by byhaskell** [php-translation/symfony-bundle#504]
Hello. Thank you for such a great bundle, I hope it will live on for 7.0 and more.

If you install Symfony 6.4 or upgrade to it, the following error will appear in the profiler when you try to edit the translation: ReferenceError: Sfjs is not defined

How to avoid it?
I did research and know that Sfjs is initialized in web_toolbar (twig) and dumped in Symfony 6.4 - it is not called, although all settings for the toolbar are positive.

**Comment by bocharsky-bw** [comment]
So everything seems working but you just noticed that error in the console? I didn't double-check that, but sounds like we may use that Sfjs faster that it was loaded on the page, something to debug more deep I think

**Comment by byhaskell** [comment]
@bocharsky-bw Thank you for your attention to my question.
Yes, I see this error in the browser console, because after I click the EDIT button, the preloader spins and nothing happens.
I also think that the script is loaded first than necessary, but I have not yet understood how to influence this.

**Comment by bocharsky-bw** [comment]
If you want to give it a try to fix it - PR is warmly welcome!

**Comment by byhaskell** [comment]
@bocharsky-bw Thank you. I will try to figure out how to do it, I have no experience with this. I understand how to do PR, but I understand how comprehensively it is possible to locally test changes in bundles. If I figure it out, I'll try to help.

**Comment by byhaskell** [comment]
@bocharsky-bw Hello. I found the reason in vendor/symfony/http-kernel/Profiler/Profiler.php on line 143 (https://github.com/symfony/http-kernel/blob/df0c04b049ddeabb3705a1b6ce1a99fe83fdd670/Profiler/Profiler.php#L143) not is being checked. I didn't find how to turn it on, maybe you have ideas?
The config is as follows:
```
#config/packages/web_profiler.yaml
when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: true

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }

```
