### ISSUE TITLE
[EditInPlace] Parameters get replace

### ISSUE THREAD

**Issue by rvanlaak** [php-translation/symfony-bundle#87]
When labels that have a parsed value get translated, the value overwrites the parameter placeholder.

````yml
title: 'Hi %name%'
# will be saved as
title: 'Howdy Richard'
```

This can be fixed by

1. Adding the translation value to the `<x-trans>` tag as a `data-value` attribute, without any replaced parameter.
2. Let the Javascript first replace the translatable label with `data-value`, so it is clear to the translator that it is a dynamic parameter.

What I'm not sure about is how we thereafter can merge the value (e.g. "Richard") back in.
